import {StyleSheet, Dimensions} from 'react-native';
import theme from './theme';

export default StyleSheet.create({
  profileImage: {resizeMode: 'center', width: '30%', height: '100%'},
  badgeImage: {
    resizeMode: 'center',
    width: '25%',
    height: '50%',
    marginBottom: 5,
  },
  floatButton: {
    position: 'absolute',
    right: 15,
    bottom: 15,
    backgroundColor: theme.palette.Jet,
    borderRadius: 25,
    width: 50,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileBlock: {
    flexDirection: 'column',
    flexWrap: 'wrap',
    borderWidth: 2,
    borderStyle: 'solid',
    padding: '5%',
    borderColor: theme.palette.Gainsboro,
    borderRadius: 15,
  },
  characterImage: {width: 200, height: 250, resizeMode: 'contain'},
  characterImageLand: {width: 150, height: 200, resizeMode: 'contain'},
  profileCharacter: {resizeMode: 'stretch', width: 150, height: 200},
  textInput100: {
    height: 40,
    width: '100%',
    borderColor: 'gray',
    borderWidth: 1,
    marginBottom: 7,
  },
  textInput20: {
    height: 40,
    width: '20%',
    borderColor: 'gray',
    borderWidth: 1,
  },
  radioButton: {marginLeft: 10},
  PokedexElementWrapper: {
    width: '100%',
    height: 70,
    backgroundColor: theme.palette.Gainsboro,
    borderRadius: 15,
    marginBottom: 5,
    flexDirection: 'row',
    alignContent: 'center',
    alignItems: 'center',
  },
  PokedexElementWrapperLand: {
    width: '100%',
    height: 70,
    backgroundColor: theme.palette.Gainsboro,
    borderRadius: 15,
    marginBottom: 5,
    flexDirection: 'row',
    alignContent: 'center',
    alignItems: 'center',
  },
  PokedexElementImageContent: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.palette.Jet,
    height: 70,
    zIndex: 10,
    borderTopLeftRadius: 15,
    borderBottomLeftRadius: 15,
  },
  PokedexSpriteView: {
    width: 50,
    height: 50,
    resizeMode: 'stretch',
    marginRight: 8,
  },
  PokedexSpriteDetailView: {
    width: 100,
    height: 100,
    resizeMode: 'stretch',
    marginRight: 8,
  },
  mapImage: {
    width: 1000,
    height: Dimensions.get('window').height,
    resizeMode: 'stretch',
  },
  pokemonArtImage: {width: 200, height: 200, resizeMode: 'stretch'},
  pokemonMove: {
    flexDirection: 'column',
    flexWrap: 'wrap',
    borderWidth: 1,
    borderColor: theme.palette.Black,
    backgroundColor: theme.palette.Gainsboro,
    width: '100%',
    height: 40,
    borderRadius: 15,
    paddingLeft: 15,
    marginVertical: 2,
    justifyContent: 'center',
  },
  pokedexContainer(customeColor = theme.palette.Gainsboro + 'ee') {
    return {
      height: '100%',
      backgroundColor: customeColor,
      alignItems: 'center',
      paddingTop: 15,
    };
  },
  createTriangle(rigthWidth, topWidth, color, rotate, adjust) {
    return {
      width: 0,
      height: 0,
      backgroundColor: 'transparent',
      borderStyle: 'solid',
      borderRightWidth: rigthWidth,
      borderTopWidth: topWidth,
      borderRightColor: 'transparent',
      borderTopColor: color,
      transform: [{rotate: `${rotate}deg`}, {translateY: adjust}],
      zIndex: 1,
    };
  },
  createButton(color) {
    return {
      width: 80,
      alignItems: 'center',
      marginHorizontal: 10,
      borderWidth: 1,
      borderRadius: 5,
      borderEndColor: theme.palette.Jet,
      backgroundColor: color,
      paddingVertical: 10,
      paddingHorizontal: 10,
    };
  },
});
